# SQL_view.py
wanted data view: '*'
table view: [VersaPLX2000_20220209_drbd, VersaPLX2000_20211229_drbd]

# Input.py
file input: '08_06_05_23_results.txt'
# Key ID: '9'
Client Name: 'b'
Date: '202204021' #format example:20210101
Disk Type: 'drbd'

# SQL_select.py
wanted data: '*'
table: [VersaPLX2000_20220209_drbd, VersaPLX2000_20211229_drbd]
statement: 'Number_of_Job = "8" AND IOdepth = "8"'

# SQL_select_two_table.py
wanted data1: '*'
table1: 'VersaPLX2000_20220209_drbd'
statement1: 'Number_of_Job = "8" AND IOdepth = "8"'
wanted data2: '*'
table2: 'VersaPLX2000_20211229_drbd'
statement2: 'Number_of_Job = "8" AND IOdepth = "8"'

# SQL_chart.py
Select_Data: 'IOPS' # IOPS / MBPS 
Table_Names: 'VersaPLX2000_20220209_drbd'
ReadWrite_Type: '"randwrite"' # read, write, randread, randwrite
Number_of_Job: '"8"'
IOdepth: '"8"'

# chart_readwrite.py
Select_Data_rw: 'IOPS' # IOPS / MBPS 
Table_Names_rw: 'VersaPLX2000_20211229_drbd'
Number_of_Job_rw: '"8"'
IOdepth_rw: '"8"'

# SQL_histogram.py
Select_Data_hist: 'IOPS' # IOPS / MBPS 
Table_hist: [VersaPLX2000_20220209_drbd, VersaPLX2000_20211229_drbd]
Readwrite_hist: '"read"' # read, write, randread, ranwrite
Number_of_Job_hist: '"8"' 
IOdepth_hist: '"8"'
Blocksize_hist: '"1M"' # 4k / 1M

# SQL_deviation.py
Standard_Value: IOPS # IOPS / MBPS
Table_Name_devi_1: 'VersaPLX2000_20211229_drbd'
ReadWrite_Type_Stan: '"randwrite"' # # read, write, randread, ranwrite
Blocksize_Stan: '"4k"' # used for one standard

Example_Value: IOPS # IOPS / MBPS
Table_Name_devi_2: 'VersaPLX2000_20211229_drbd'
ReadWrite_Type_Ex: '"randwrite"' # # read, write, randread, ranwrite